language: java

dist: trusty
sudo: false

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 10 "OpenJDK"
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL

script:
  - ./gradlew build